LLM_Backend: openai

OpenAI_api:
  url: https://api.openai.com/v1
  key: 
  model:

  inference:
    max_tokens: 2048
    temperature: 0.2

Translate_Config:
  max_attempts: 3
  context_num: 8

  bracket_pre_post_proc: True